site_name: OCI Utils (AB)
site_dir: build

nav:
  - Home: index.md
  - Getting Started: intro.md
  - Changelog: changelog.md
  - Command Reference: commands.md

theme:
  name: terminal
  palette: dark
