name: docs

permissions:
  contents: read
  id-token: write
  pages: write

on:
  push:
    branches:
      - master
    paths: &paths
      - src/docs/**
      - .github/workflows/docs.yaml
  pull_request:
    branches:
      - master
    types: [opened, synchronize]
    paths: *paths

jobs:
  docs:
    if: github.event_name != 'push' || github.ref != 'refs/heads/master' # when synchronize
    runs-on: ubuntu-latest
    steps:
      # build site
      - { uses: actions/checkout@v4 }
      - { uses: actions/setup-python@v5, with: { python-version: '3.12' } }
      - { uses: snok/install-poetry@v1, with: { version: '2.1.4' } }
      - shell: bash
        run: |
          set -eux -o pipefail
          cd src/docs
          poetry install
          poetry run mkdocs build

      # upload
      - uses: actions/upload-artifact@v4
        with: &mkdocs_site_artifact
          name: mkdocs-site
          path: src/docs/build
          retention-days: 1

  pages:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' # when merged
    runs-on: ubuntu-latest
    steps:
      # download
      - { uses: actions/download-artifact@v4, with: *mkdocs_site_artifact }

      # github pages
      - { uses: actions/configure-pages@v5 }
      - { uses: actions/upload-pages-artifact@v3, with: { path: 'src/docs/build' } }
      - { uses: actions/deploy-pages@v4 }
