name: latest

permissions:
  contents: write

on:
  push:
    branches:
      - master
    paths: &paths
      - version.txt
      - .github/workflows/latest.yaml
  pull_request:
    branches:
      - master
    types: [opened, synchronize]
    paths: *paths

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      BUILD_VERSION: ${{ steps.version.outputs.VERSION }}
    steps:
      # build site
      - { uses: actions/checkout@v4 }
      - { uses: actions/setup-java@v5, with: { distribution: 'temurin', java-version: '21', cache: 'gradle' } }
      - run: ./gradlew build
      - id: version
        run: echo "VERSION=$(cat version.txt)" >> "${GITHUB_OUTPUT}"

      # upload
      - uses: actions/upload-artifact@v4
        with: &latest_jar_artifact
          name: latest
          path: build/bins/*
          if-no-files-found: 'error'
          retention-days: 1

  publish:
    needs: [ build ]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' # when merged
    runs-on: ubuntu-latest
    steps:
      # download
      - { uses: actions/download-artifact@v4, with: *latest_jar_artifact }
      - run: |
          echo "debugging where the latest_jar_artifact went: "
          find . -name '*.jar'
          echo "debugging what files we see: "
          find .

      # publish
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.build.outputs.BUILD_VERSION }}
          name: Release v${{ needs.build.outputs.BUILD_VERSION }}
          # body: Initial release of the project.
          fail_on_unmatched_files: true
          files: |
            build/bins/**
